# ==========================================
# Configurazione Spring Boot e H2 (Commentata, per storico)
# ==========================================
#spring.application.name=lignosuiteapi
##spring.datasource.url=jdbc:h2:mem:falegnameriadb
#spring.datasource.url=jdbc:h2:file:./data/falegnameriadb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=pa
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
# ==========================================
# Configurazione Spring Boot e PostgreSQL
# ==========================================
spring.application.name=lignosuiteapi
# URL del database in locale
spring.datasource.url=jdbc:postgresql://localhost:5432/lignosuitedb
spring.datasource.driverClassName=org.postgresql.Driver
# Credenziali Postgres
spring.datasource.username=postgres
spring.datasource.password=admin
# ==========================================
# IMPOSTAZIONI JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ==========================================
# Configurazione Email (Gmail)
# Le credenziali sono nel file application-secret.properties
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# ==========================================
# Configurazione per il caricamento di file
# ==========================================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# ==========================================
# Inclusione del profilo "secret" per le configurazioni sensibili
# ==========================================
spring.profiles.include=secret
