# Configurazione Spring Boot e H2
## Nome dell'applicazione
#spring.application.name=lignosuiteapi
## Configurazione Database H2 (in questo modo i dati vengono salvati in memoria)
##spring.datasource.url=jdbc:h2:mem:falegnameriadb
## Configurazione Database H2 con file locale
#spring.datasource.url=jdbc:h2:file:./data/falegnameriadb
## per accedere dal browser all'applicazione h2
## http://localhost:8080/h2-console
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=pa
## Permette di vedere la console del database nel browser
#spring.h2.console.enabled=true
## Sincronizza le tabelle del DB con le classi Java (Entity) automaticamente
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
# Configurazione Spring Boot e PostgreSQL
# Nome dell'applicazione
spring.application.name=lignosuiteapi
# ==========================================
# CONNESSIONE A POSTGRESQL
# ==========================================
# URL del database (presuppone che il database si chiami 'falegnameriadb' e giri in locale)
spring.datasource.url=jdbc:postgresql://localhost:5432/falegnameriadb
spring.datasource.driverClassName=org.postgresql.Driver
# Inserisci qui username e password che hai scelto quando hai installato Postgres!
# (Di default l'utente di solito è 'postgres')
spring.datasource.username=postgres
spring.datasource.password=admin
# ==========================================
# IMPOSTAZIONI JPA / HIBERNATE
# ==========================================
# Permette a Hibernate di creare/aggiornare le tabelle automaticamente in base alle tue classi Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Specifica il dialetto corretto per Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
